"use strict"

const fs = require("node:fs")
const path = require("node:path")

const ROOT = path.resolve(__dirname, "..")
const OUTPUT = path.join(ROOT, "docs", "rules-coverage.md")

const RULES = [
	[1, "Introduction", "data/core", "covered"],
	[2, "Components", "data/assets", "partial"],
	[3, "Terminology and abbreviations", "core", "partial"],
	[4, "Game setup", "systems/setup", "partial"],
	[5, "Determining victory", "systems/turn", "partial"],
	[6, "Sequence of play", "systems/turn + states/turn", "partial"],
	[7, "Strategy cards", "systems/cards + systems/events", "partial"],
	[8, "Orders", "systems/orders + states/turn", "partial"],
	[9, "Stacking", "systems/map", "covered"],
	[10, "Movement", "systems/map + states/activation", "covered"],
	[11, "Combat", "systems/combat + states/combat", "covered"],
	[12, "Strategic Redeployment", "systems/map + states/activation", "covered"],
	[13, "Supply", "systems/map + systems/logistics", "covered"],
	[14, "Replacements", "systems/replacements + states/turn", "covered"],
	[15, "Weather", "systems/weather + systems/combat + systems/map + systems/invasions", "covered"],
	[16, "Partisans", "systems/events + states/action", "partial"],
	[17, "Neutrals", "systems/neutrals + states/action", "partial"],
	[18, "Resources", "systems/resources + systems/turn", "partial"],
	[19, "National restrictions", "systems/restrictions", "partial"],
	[20, "Campaign scenario", "systems/setup", "partial"],
]

const OPTIONAL = [
	["allied_2_24_exclusive_1941", "Only one of Allied events 2 and 24 in 1941", "implemented"],
	["no_invasions_before_summer_42", "No Allied invasions before Summer 1942", "implemented"],
	["sunny_italy", "Naples is Limited Supply in Fall/Winter", "implemented"],
	["time_of_mud", "German Panzer limits in Fall 1941 rounds 2-3", "implemented"],
]

function makeReport() {
	const lines = [
		"# BTB rules coverage",
		"",
		"> Generated by `npm run report:coverage:update`. Rulebook v1.3 and its Clarifications are authoritative.",
		"",
		`Core rules: ${RULES.filter((row) => row[3] === "covered").length}/20 covered.`,
		"",
		"## Numbered rules",
		"",
		"| Rule | Topic | Module | Status |",
		"| --- | --- | --- | --- |",
		...RULES.map(([number, topic, module, status]) => `| ${number} | ${topic} | ${module} | ${status} |`),
		"",
		"## Optional rules",
		"",
		"| Option | Rule | Status |",
		"| --- | --- | --- |",
		...OPTIONAL.map(([key, label, status]) => `| ${key} | ${label} | ${status} |`),
		"",
	]
	return {
		markdown: lines.join("\n"),
		rules: RULES,
		optional: OPTIONAL,
	}
}

function main() {
	const report = makeReport()
	if (process.argv.includes("--write")) {
		fs.writeFileSync(OUTPUT, report.markdown, "utf8")
		console.log(`Wrote ${OUTPUT}`)
	} else process.stdout.write(report.markdown)
}

if (require.main === module) main()

module.exports = { OPTIONAL, RULES, makeReport }
